//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Modules.AutoMod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoModRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoModRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Modules.AutoMod.AutoModRessources", typeof(AutoModRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Konfiguration &apos;{0}&apos; ist in der Regel &apos;{1}&apos; nicht gesetzt.
        /// </summary>
        internal static string Error_ConfigUnset {
            get {
                return ResourceManager.GetString("Error_ConfigUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Regel ist bereits aktiv.
        /// </summary>
        internal static string Error_RuleAlreadyActive {
            get {
                return ResourceManager.GetString("Error_RuleAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Regel &apos;{0}&apos; existiert nicht.
        /// </summary>
        internal static string Error_RuleDoesNotExist {
            get {
                return ResourceManager.GetString("Error_RuleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Regel &apos;{0}&apos; ist nicht aktiv.
        /// </summary>
        internal static string Error_RuleNotActive {
            get {
                return ResourceManager.GetString("Error_RuleNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        internal static string Identifier_Active {
            get {
                return ResourceManager.GetString("Identifier_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaktiv.
        /// </summary>
        internal static string Identifier_Inactive {
            get {
                return ResourceManager.GetString("Identifier_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Regel wurde aktiviert.
        /// </summary>
        internal static string Message_RuleActivated {
            get {
                return ResourceManager.GetString("Message_RuleActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Regel wurde deaktiviert.
        /// </summary>
        internal static string Message_RuleDisabled {
            get {
                return ResourceManager.GetString("Message_RuleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert wurde aktualisiert.
        /// </summary>
        internal static string Message_SavedValue {
            get {
                return ResourceManager.GetString("Message_SavedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert &apos;{0}:{1}&apos; ist aktuell auf &apos;{2}&apos; gesetzt.
        /// </summary>
        internal static string Message_SetValue {
            get {
                return ResourceManager.GetString("Message_SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare AutoMod-Regeln.
        /// </summary>
        internal static string Title_AvailableRules {
            get {
                return ResourceManager.GetString("Title_AvailableRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Automod-Einstellungen für &apos;{0}&apos;.
        /// </summary>
        internal static string Title_PossibleConfigs {
            get {
                return ResourceManager.GetString("Title_PossibleConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Du schreibst zu schnell.
        /// </summary>
        internal static string Validation_Spamming {
            get {
                return ResourceManager.GetString("Validation_Spamming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Zu viele Caps.
        /// </summary>
        internal static string Validation_TooManyCaps {
            get {
                return ResourceManager.GetString("Validation_TooManyCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Zu viele Emotes.
        /// </summary>
        internal static string Validation_TooManyEmotes {
            get {
                return ResourceManager.GetString("Validation_TooManyEmotes", resourceCulture);
            }
        }
    }
}
