//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Modules.MarioKart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarioKartRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarioKartRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Modules.MarioKart.MarioKartRessources", typeof(MarioKartRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei der Datenübertragung.
        /// </summary>
        internal static string Error_CannotParseInformation {
            get {
                return ResourceManager.GetString("Error_CannotParseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte 6 Zahlen eingeben.
        /// </summary>
        internal static string Error_Enter6Numbers {
            get {
                return ResourceManager.GetString("Error_Enter6Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Strecke und die CC an! (!mkwr  MKS 150).
        /// </summary>
        internal static string Error_MkwrSyntax {
            get {
                return ResourceManager.GetString("Error_MkwrSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell kann kein Rennen zurückgesetzt werden.
        /// </summary>
        internal static string Error_NotRevertable {
            get {
                return ResourceManager.GetString("Error_NotRevertable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team - Unterschied - Gegner
        ///{0} - {1} - {2}.
        /// </summary>
        internal static string Message_FinalResult {
            get {
                return ResourceManager.GetString("Message_FinalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team - Unterschied - Gegner
        ///Diese Runde: {0} - {1} - {2}
        ///Total: {3} - {4} - {5}.
        /// </summary>
        internal static string Message_RaceResult {
            get {
                return ResourceManager.GetString("Message_RaceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charakter.
        /// </summary>
        internal static string WR_Char {
            get {
                return ResourceManager.GetString("WR_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleiter.
        /// </summary>
        internal static string WR_Glider {
            get {
                return ResourceManager.GetString("WR_Glider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart.
        /// </summary>
        internal static string WR_Kart {
            get {
                return ResourceManager.GetString("WR_Kart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runde 1.
        /// </summary>
        internal static string WR_Lap1 {
            get {
                return ResourceManager.GetString("WR_Lap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runde 2.
        /// </summary>
        internal static string WR_Lap2 {
            get {
                return ResourceManager.GetString("WR_Lap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runde 3.
        /// </summary>
        internal static string WR_Lap3 {
            get {
                return ResourceManager.GetString("WR_Lap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reifen.
        /// </summary>
        internal static string WR_Tires {
            get {
                return ResourceManager.GetString("WR_Tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weltrekord: {0} - {1} - {2}.
        /// </summary>
        internal static string WR_Title {
            get {
                return ResourceManager.GetString("WR_Title", resourceCulture);
            }
        }
    }
}
