//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Modules.AutoRole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoRoleRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoRoleRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Modules.AutoRole.AutoRoleRessources", typeof(AutoRoleRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist keine Gültige Aktion!\nVerfügbar: add, list, delete&quot;.
        /// </summary>
        internal static string Error_InvalidAction {
            get {
                return ResourceManager.GetString("Error_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rolle &apos;{0}&apos; wird nicht automatisch verteilt oder ist nicht vorhanden.
        /// </summary>
        internal static string Error_InvalidRole {
            get {
                return ResourceManager.GetString("Error_InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Rolle hat Administratorrechte und wird nicht automatisch verteilt..
        /// </summary>
        internal static string Error_PermissionTooHigh {
            get {
                return ResourceManager.GetString("Error_PermissionTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rolle &apos;{0}&apos; wurde nicht gefunden. Bitte ID verwenden.
        /// </summary>
        internal static string Error_RoleNotFound {
            get {
                return ResourceManager.GetString("Error_RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisches Verteilen beendet.
        /// </summary>
        internal static string Message_DeletedRegistration {
            get {
                return ResourceManager.GetString("Message_DeletedRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rolle wird nun automatisch verteilt.
        /// </summary>
        internal static string Message_NewAutoRole {
            get {
                return ResourceManager.GetString("Message_NewAutoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch verteilte Rollen auf dem Server.
        /// </summary>
        internal static string Title_AutomaticDistributedRoles {
            get {
                return ResourceManager.GetString("Title_AutomaticDistributedRoles", resourceCulture);
            }
        }
    }
}
