//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Modules.Event {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Modules.Event.EventResources", typeof(EventResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die eingegebene Zeit konnte nicht interpretiert werden. Versuche es mit &apos;20:00&apos;, &apos;20&apos; oder &apos;1.1.2025 16:00&apos;.
        /// </summary>
        internal static string Error_TimeNotResolved {
            get {
                return ResourceManager.GetString("Error_TimeNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event um {0}.
        /// </summary>
        internal static string EventTitle {
            get {
                return ResourceManager.GetString("EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Kann ({0}).
        /// </summary>
        internal static string Field_Can {
            get {
                return ResourceManager.GetString("Field_Can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Verhindert ({0}).
        /// </summary>
        internal static string Field_Cant {
            get {
                return ResourceManager.GetString("Field_Cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔼 Einspringer ({0}).
        /// </summary>
        internal static string Field_Sub {
            get {
                return ResourceManager.GetString("Field_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❓ Unsicher ({0}).
        /// </summary>
        internal static string Field_Unsure {
            get {
                return ResourceManager.GetString("Field_Unsure", resourceCulture);
            }
        }
    }
}
